# Generated by Django 4.1 on 2022-08-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_tag_order_book_order_customer_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
    ]
